= ASE Service Proxy Delegate Service
ifndef::compositing[]
:author: cyotee doge
:email: cyotee@syscoin.org
:revdate: 2022-02-19
:revnumber: 0.1
:revremark: Initial draft.
:toc:
:toclevels: 6
:sectnums:
:data-uri:
:stem: asciimath
:pathtoroot: ../../
:imagesdir: {pathtoroot}
:includeprefix: {pathtoroot}
:compositing:
endif::[]

The ASE Service Proxy is the base proxy implementation.
The Service Proxy Factory will deploy Minimal Proxies delegating to the Service Proxy Delegate Service.
The Service Proxy provides the function selector based implementation mapping.
A new Minimal Proxy instance is initialized by the Service Proxy Factory with the functional selector to address mappings for the configured Delegate Services.

The Service Proxy Delegate Service also serves as the proxy for interacting with the Service Proxy Factory, Delegate Service Registry, and the Delegate Service Factory.
When the Service Proxy Delegate Service is deployed, it will deploy the other core components of the ASE.
The Service Proxy Delegate Service will initialize itself with the storage configuration for the deployed delegate services.
This includes:

* Map deployed delegate services as proxy implementations.
* Store the deployed delegate services for use as a Delegate Service Registry.
* Store the deployed Delegate Service Registry for use as a Service Proxy Factory and Delegate Service Registry.

The Service Proxy implements a `fallback() payable` function.
This `fallback() payable` function uses the implicit variable `msg.sig` to lookup which address to use as the target of a `DELEGATECALL`.
This is the Delegate Service configured when the Service Proxy was deployed from the factory.
The transaction data is forwarded to the target Delegate Service.
The target Delegate Service then executes it's implemented logic using the storage of the Service Proxy that issued the `DELEGATECALL`.

A Service Proxy may need more complex transaction processing that is domain specific.
This is defined in the Transaction Router design pattern.

== IServiceProxy



// TODO include NatSpec generated docs.