= Deterministically Dynamic Storage Allocation
ifndef::compositing[]
:author: cyotee doge
:email: cyotee@syscoin.org
:revdate: 2022-02-19
:revnumber: 0.1
:revremark: Initial draft.
:toc:
:toclevels: 6
:sectnums:
:data-uri:
:stem: asciimath
:pathtoroot: ../../../
:imagesdir: {pathtoroot}
:includeprefix: {pathtoroot}
:compositing:
endif::[]

*This standard is under active development. Expect breaking changes.*

Deterministically Dynamic Storage Allocation (DDSA) takes advantage of built-in hashing functionality of the EVM to allocate storage slots using the bytecode of struct libraries.
Structs are used to force all storage interaction through storage pointers.
This ensures there will be no storage collisions between dynamically sized datatypes.

An example can be seen the following code sample.

[source, solidity]
----
include::../../../contracts/types/primitives/String.sol[lines="6..16"]
----

The datatype libraries for the ASE are implemented as a struct containing just the desired primitive datatype.
The name of the library must be the same as, or directly descriptive of, the primitive datatype.
This provides a standardized implementation that results in consistent bytecode.
By enforcing the implementation of all datatypes as libraries defining custom structs, a consistent bytecode for that datatype is defined.

A utility library is implemented to facilitate use of the datatype library.
An example can be seen here.

[source, solidity]
----
include::../../../contracts/types/primitives/String.sol[lines="18..-1"]
----

A constant is calculated by hashing the bytecode of the library defining the datatype struct.
This is made available with the standard `_structSlot()` function.
The usage of bytecode hashes as storage slots is the foundation of the storage standard used in the ASE.

The standard `_saltStorageSlot(bytes32)` function provides consistent calculation of a 
The standardization of the struct library implementations, and the hashing of that bytecode ensures that the correct struct is being used to access storage.

Each datatype storage library also implements a standard `_layout(bytes32)` function used to bind a storage pointer to an instance of the struct.
While Solidity does not have full polymorphism, this process allows us to leverage the pseudo-polymorphism that's available.

From here, a modification of the Diamond/Application Storage design pattern is applied.
In th Diamond/Application Storage design pattern, the state variables for a particular implementation is composed into one or more structs.
The storage slot is also defined using a hash of some value.
The design pattern has no opinion on the values to hash.
While this is appropriate for a design pattern, the ASE framework asserts an opinion.

One of the common problems with applying Diamond/Application Storage is the complexities around using dynamic length datatypes, such as strings.
While storage slot packing can be used, this also introduces a potential conflict.
An update to a facet applying Diamond Storage may introduce an incompatibility with how the storage has been managed until the update is applied.
The ASE applies Diamond/Application Storage to the base datatype library usage.
And example can be seen below.

[source,solidity]
----
include::../../../contracts/test/messenger/storage/MessengerStorage.sol[lines="14..20"]
----

This process of wrapping the datatype libraries in a domain specific struct forces dynamic length datatypes into storage pointers.

A datatype storage library is implemented to to operate on the Diamond/Application struct following the same conventions as the primitive datatype libraries.
An example can be seen in this code sample.

[source,solidity]
----
include::../../../contracts/test/messenger/storage/MessengerStorage.sol[lines="22..-1"]
----

The Diamond/Application datatype storage library implements the same functions as a primitive datatype library.
The `_structSlot()` also exposes the creation code hash of the datatype library.
Further, the standard `_saltStorageSlot(bytes32)` function combines the default storage slot for each of the composed datatypes.
Further, the standard `_layout(bytes32)` function still binds a storage slot to the datatype.
This helps ensure that the structure for a set of state variables is consistently stored based on that structure.
This way, in the event of a failure to implement the libraries to access the storage previously unused storage is accessed.
This helps protect existing data.
This will be improved by externalizing the storage libraries for reuse in deployed contracts.
A datatype storage library registry will be implemented for dynamic library linking during execution.

So far this has covered how storage is managed internally.
But state variables exists in service of domain logic implemented in service of an interface.
This is why the usage of datatype structs with Diamond Storage within the ASE is bound to the interfaces exposed by particular facets.
And example of this can be seen below.

[source,solidity]
----
include::../../../contracts/test/messenger/logic/MessengerLogic.sol[lines="9..-1"]
----

This example is of a library that implements the desired domain logic.
During development some are implemented as abstract contracts.
These will be refactored to external libraries as part of implementing the dynamic library linking.
The domain logic contract includes a parameter for the storage slot salt to use when operating on storage.
This standard decouples domain logic from the storage slot range to operate upon.
This domain logic is expected to be used in a Delegate Service implementation that exposes an interface.
Future implementations will refactor these domain logic contracts into libraries to be executed using a reverse proxy library.

An example of an externalizing contract cen be seen below.

[source,solidity]
----
include::../../../contracts/test/messenger/Messenger.sol[lines="9..-1"]
----

This externalizing contract exposes the following interface.

[source,solidity]
----
include::../../../contracts/test/messenger/interfaces/IMessenger.sol[lines="4..-1"]
----

The domain logic uses the interface ID this is to serve as the salt for the storage slot calculation.
This allows for two main features.

First, the usage is a Diamond Storage struct can be grouped by the interface ID that struct supports.
This allows for safely reusing Diamond Storage structs in other facets to support other interfaces.
Because the Diamond Storage struct is using a deterministic storage slot computed from its structure, it can be reliably allocated to a range of storage slots.
And the complex datatypes that consume a dynamic amount of storage are deterministically distributed to other storage slots based on the base storage slot.
This greatly minimizes the chance of storage slot collisions across facets, while promoting code reuse.

Second, this allows for facets to reliably interact with storage across interfaces by having a reliable process for calculating the storage slots used in service of that interface.
This way the functionality and flexibility of a proxy is greatly enhanced due to the consistent storage allocations.
And remains consistently safe.
While the chance for storage slot collisions typically goes up as more Diamond Storage structs are used; the cascading distribution of slots distributes the chance across an ever greater range.
This is akin to the solution for the Infinite Hotel Paradox.
By including the set of possible values in the distribution formula for that set of values, you get an ever expanding variance in the distribution.
A simple diagram explaining this is below.

image::images/architecture/design_patterns/daosys-design_patterns-ddsa.drawio.svg[align=center]

The storage slots for the discrete data types are combined using a bitwise XOR operation.
This does abstract out the exact order of the datatypes in the Diamond Storage struct.
This is abstraction is intentional as it should catch an unsafe ordering of state variables during testing.
A possible improvement is to use an order dependent bitwise operation.
This will need further research.
Then to group the Diamond Storage structs by the interface they serve, the interface ID is applied using bitwise XOR.
This results in a consistent prefix for all the storage slots used by an interface.
Overall, this replicates a primary to foreign key relationship for calculating the storage slots used by a facet.
This allows for using the EVM storage solution like a relational database.
Together, this allows for a on-chain factory that can deploy proxy and initialize them any combination of facets without encountering a storage slot collision for an any arbitrary set of facets.