ifndef::compositing[]
:author: cyotee doge
:email: cyotee@syscoin.org
:revdate: 2022-03-25
:revnumber: 0.1
:revremark: Initial draft.
:toc:
:toclevels: 6
:sectanchors:
:sectlinks:
:sectnums:
:data-uri:
:stem:
:pathtoroot: ../../
:imagesdir: {pathtoroot}
:includeprefix: {pathtoroot}
:compositing:
endif::[]

== Technology Summary

The innovative software architecture that allows DAOSYS to pioneer a revolution in DAOs is the Autonomous Service Engine, (ASE).
This introduces a revolution allowing DAOs to become more autonomous and fully decentralized.
The ASE iterates on burgeoning standards like Diamond proxies to apply AMM functionality for more flexible capabilities.

The technology that enables automated market making is the CREATE2 operation in EVM implementations.
This allows a smart-contract to deploy another smart contract, this is typically call the Factory design pattern.
Protocols like Balancer and Uniswap provide the ability to create permissionless liquidity pools.
The limit of these implementations is the immutable nature of smart-contract bytecode.
They can only deploy a single type of contract.

Protocols like Aavegotchi have pioneered smart-contract architecture by iterating on the proxy capabilities of the EVM to advance the Factory design pattern.
Smart-contract proxies take advantage of the DELEGATECALL EVM OPCODE to allow a smart-contract to reuse the logic implemented in other smart-contracts.
The Autonomous Service Engine advances this innovation with an infinitely flexible Diamond Factory design.
The Diamond Factory design factory combines the Factory and Diamond design patterns to deploy configurable proxies.
This allows for infinitely composable proxies.

== Economic Summary

DAOSYS uses the ASE as an economic abstraction layer.
The base structure of a DAOSYS liquidity pool relies on an underlying market that provides an interest rate.
The integrations and defi solutions available through the ASE use rebasing tokens to index that underlying market.
This indexing process is aggregated into two tokens, the Treasury Token and the Market Index Token.
Users receive the Treasury Token to represent their contribution to the treasury and the interest due to them.
The Market Index Token is used to index interest actualized from the underlying markets and to provide liquidity for that interest.

This two token market indexing process compartmentalizes the risk of deploying capital to the market.
The two tokens for an effective A and B class of investment tranches.
The vault does not accept deposits, it sells users the Treasury Token as algorithmic bond on the interest earned across the vault.
The Market Index Token is used as the B tranche.
The Treasury Token acts as the A tranche.
When the vault purchases new assets or actualizes interest for its market position that is sold into the Market Index Token liquidity.
Effectively paying interest to the B tranche.
There is a soft cap on interest earned in the B tranche because the Market Index Token is paired with liquidity of the Treasury Token.
This means that holders of the Treasury token are earning interest from both tranches.
But, must sell through the a tranche, dispensing further interest to other holders, to exit through the B tranche.

== Governance Summary

DAOSYS has no top level governance.
Applying the AMM model to DAOs means that users create their own treasuries for specific ventures.
These treasuries may apply a variety of governance solutions along with their treasuries.
This allows for a compartmentalization of the politics that arise with any governance solution from the actual treasury management.

// image::images/governance/daosys-governance-abstract.drawio.svg[align=center]

Under this model, the Syscoin Foundation behaves more like a software vendor.
The factory makes open-source reference implementations of defi components available to compose into treasuries.
Updates to these smart-contracts are available for deploying new pools that may be added to a DAO.
This removes the need for a top-level governance solution that decides whether to include an update because users are free to create new pools.

A user creates a DAO by selecting which vaults and bond markets they would like to include.
These vaults may come from four sources.

* Reuse an existing vault used by other DAOs, mingling treasuries.

This works best for when users wish to maintain their position in one DAO, but want to add more pools to form a new DAO.

* Recreate a copy of an existing vault.

If it's not broke, don't fix it.
The investment strategy implemented in a vault can be used across several instances of vault pools.
This works well for new DAOs that wish to replicate the financial strategies of an existing DAO.
Also for when the new DAO would like to invest in other DAOs using the same strategy.

* Deploy a new pool comprising a new investment strategy.

A user may wish to create a new DAO reusing functionality available from the factory, but configured in a novel manner.
The flexibility available in the ASE means that even a simple strategy has several configuration options.
This is useful for when a DAO wishes to adopt a novel investment strategy that might not have been previously viable.

* Deploy a new pool with custom code.

The Syscoin Foundation makes internal decisions regarding what smart-contracts are available through the factory similar to open source software development.
Because this only concerns the software available from the foundation, this does not need to be open to public governance.
When the community at large wishes to release custom code outside the foundation, a user may use the factory to deploy their own factory offering their custom code.
This new factory inherits the offerings of the parent factory and may add their own modules.

These pools form the foundation of the DAO.
Autonomous and permissionless liquidity pools that act as the agreed upon foundation for DAO treasury management.
From there users may launch further liquidity pools that may accept the DAOs Treasury Token for deposit.
These form the Roundtables for managing ventures within the DAO.
The Roundtables compartmentalize management teams, Councilors, of the various ventures being executed under a DAO's mission statement.
A Roundtable typically does not have it's own governance token, instead using a Council Token used to resolve disputes by executing buyout options.

From the Roundtables, any Councilor may use their contribution to the Roundtable to launch a bond offering for a Quest.
Quests define the bounty award and terms for completing a task.
The Councilor that issues the quest puts their share of the treasury in escrow to fund the Quest.
The interest being earned from that underlying position is then split to fund the bounty, compound into that position, and to sell on the bond market.
This ensures that Questors know the payment for work they deliver is secured.
And protects the Councilor from failure to deliver.