= Masternode Yield Farming as a DAOSYS Usecase
ifndef::compositing[]
:author: Ian Moore
:email: imoore@syscoin.org
:revdate: 2022-07-01
:revnumber: 0.1
:revremark: Initial draft.
:toc:
:toclevels: 5
:sectnums:
:data-uri:
:stem: asciimath
:pathtoroot: ../
:imagesdir: {pathtoroot}
:includeprefix: {pathtoroot}
:compositing:
endif::[]

== DAOSYS Introduction

The objective of a decentralized autonomous organization (DAO) is to solve the principal-agent dilemma. This dilemma is a result of misaligned incentives where agents acting in a system are incentivized towards their own benefit over the benefit of a principle or other agents acting within the system. Typically, these are found in centralized systems where the central acting authority is the main compromised agent. The DAO solves this by decentralizing the governance process by utilizing smart contracts running on open source blockchains.

The first inception of the DAO concept happened in May 2016 out of the Ethereum community, which was known as Genesis DAO, and was built as a smart contract on the Ethereum blockchain. However, this resulted in the well known DAO Hack which resulted in the draining of $60M USD worth of funds from its treasury. Today, there are many DAOs in operation with Uniswap, Aave and Maker DAO being amongst the most popular. However, these DAOs still fundamentally violate the core value proposition of self sovereignty that crypto currency promises, where DAOs currently take ownership of capital managed in a treasury controlled by a few individuals. This is the problem that DAOSYS intends to address.

DAOSYS vision is to operate like a pure automated market maker (AMM) and be implemented in a manner that does not require external controls. It addresses this core issue via its new Autonomous Service Engine (ASE) technology hence allowing DAOs to be more autonomous and fully decentralized. One of the interesting by-products of this technology will allow users to test, implement and realize countless decentralized finance (DeFi) usecase designs.


== Masternode Yield Farming

=== Syscoin Masternodes
Masternodes are special nodes in a blockchain infrastructure that perform special roles in governing the blockchain. They typically verify new blocks of transaction, and operate on a collateral-based system where operators need to own a certain amount of the cryptocurrency where the node owners are rewarded with guaranteed earnings at intermittent intervals. They were first implemented in 2014 on the Dash network, which is a fork of Bitcoin. Since then, many other crypto projections began implementing them and were popularized during the bull run that preceded the 2nd Bitcoin halvening in 2016.

Syscoin's masternode network went live in June 2019 for their 3.0 release. The collateral requirement to operate a Syscoin masternode is 100,000 SYS. At the time of this writing (Aug 2022), there are approximately 2,500 masternodes in the Syscoin network representing 38.5% of locked supply. Operators currently receive ~14 SYS base rewards per day. As a seniority benefit, Masternode operators receive a 35% bonus to their base reward after one year, and a 100% bonus after two and a half years

=== Yield Farming
Yield farming is a technique that uses DeFi to maximize returns where investors submit liquidity to a decentralized application (ie, dApp) to earn yield on their principle using various methods. These methods are classified into four main types which include: staking, lending, borrowing, and utilizing liquidity providers, which is largely done on a decentralized exchange (DEX). This technology is facilitated via blockchain smart contracts (first popularized by the Ethereum protocol in 2015), which are pieces of code that automate financial agreements between two or more parties in a trustless manner.

=== Putting it together
In Dec 2021, Syscoin released the first stage of its Network Enhanced Virtual Machine (NEVM) which utilizes the Ethereum Virtual Machine (EVM). In the coming months (from the time of this publication), this will include a Zero Knowledge Proof (ZKP) system to build layer 2 (L2) scalable applications, and one of the first of these applications will be DAOSYS.

Syscoin plans to incentivize masternode operators where they can put yields to work by investing them into a DeFi liquidity provider which will be automated in a trustless manner through DAOSYS. Hence, extending the Syscoin ecosystem, and increasing daily volumes. This system of trustlessly investing Masternode yields into a DeFi liquidity provider is what we call Masternode Yield Farming, which will serve as the first intended usecase for DAOSYS. This will be the first of its kind in the crypto space.

== Masternode Reward Simulations
Currently, there are approximately 2,500 masternodes running on the Syscoin network. For this case study we run a 5-year projection analysis on an additional 400 masternodes, while at the same time factoring in network growth. The Syscoin network generates a block every 2.5 minutes generating ~86 SYS of base rewards per block (at the time of publication) with an additional 10.55 SYS of NEVM rewards and an additional 5.275 SYS of masternode minimum subsidy. Also, as transactions on the NEVM require gas, there are also SYS tokens simultaneously being burned which need to be accounted for. For this, we assume a burn rate akin to that of Ethereum's under the assumption of an equivalent rate of adoption. Hence, to account for the global burn rate, we applied a predictive log-log model using Etheruem's transaction fee data. Finally, since nodes are continually entering and leaving the network, each node has a different level of seniority, thus we applied a seniority scaling factor which was estimated using a loss function. We applied all these components into our model to estimate daily supply growth of the network, along with its respective confidence intervals. With this tokenomics model, we estimated the expected share a typical node contributes to the network on a daily basis. Finally, with expected share, we estimated the 5-year output of 400 new masternodes; see Table 1 (below) for details.

To estimate price projections, we began with the assumption that price could swing anywhere between $0.25 to $25 USD until Jan 2027 with an upward log growth trend that is typically associated with most successful crypto projects. To simulate error, we applied a multiplicative error term to the log-growth term using an ARIMA(1,1,1) which was scaled to fluctuate between the range of 0 and 1. Using this setup, we generated a collection of Monte Carlo simulations to estimate price; see Fig 1. and Table 2 for details. We used these price projections to determine the conversion of SYS rewards in USD, which are detailed in Table 3.

== DAOSYS Simulator
To realize proper tokenomics design, from an engineering perspective, it is highly inefficient to invest resources into development without first conducting a proper simulations of the design to test specifications for various outcomes. This is what every DeFi project in the crypto space is not doing. This is why we are introducing an open source python package to simulate various sandboxed components of DAOSYS so that project engineers, managers and designers can pre-plan outcomes prior to investing valuable resources into development.

With this tool, DAOSYS designers can utilize the plug and play components of our simulator to build tokenomics mockups for business planning purposes so that teams can come together and get collective consensus alongside potential users and investors. Here, we will cover the main components of the simulator, so that potential users of the system can get an idea of what to expect.
* Agents: entities that engage with the system, and are subcategorized into tokens and users
* Events: agnostic events that take place within the system (eg, mint, deposit, withdraw, swap, and rebase)
* Actions: event actions that are fe into the system performed by agents; they can either be single stand-alone independent event actions or chained together with dependency
* Liquidity Pools: pool of two token agents managed by constant product trading
* Orchestrator: manages agents and actions working within the system
* Event Queue: queue of storable actions
* Event Executor: final step which executes queue of action events

The aforementioned components are detailed in Fig. 2 (below) which illustrate how these pieces interact with one another.

We currently have a working alpha version of the simulator which is currently available on  Syscoin's github page. This simulator is being built alongside DAOSYS, and Syscoin is using this to understand design considerations of DAOSYS's first usecase (ie, Masternode Yield Farming). Since the simulator is still in the alpha stage, the setup is currently not exhibiting its full intention. However, a downloadable demo of this tool is ready for others in the community to begin using. Refer to Fig. 3 for a primitive setup of how a masternode yield farming simulation would work.

The purpose of this tool is primarily for the design aspect of DAOSYS, and is still in its early stages of development. The next stage in the development is to feed the output of mathematical models, such as the one outlined above in Section 3 into the simulator framework so that we can test more realistic edge cases to build a more robust system. The final goal is to bring this system to a level of maturity so that it can be utilized in parallel with the contracts in real time. Hence, opening up DeFi to a more scientific way of design, test, and implementation.

== Summary
The goal of this discussion is to introduce the concept of Masternode Yield Farming as DAOSYS's initial usecase. We also highlight the benefits of investing into a Syscoin masternode, and the promise that DAOSYS will deliver as an extension to the network.

At the time of this publication (Aug 2022), the cost of acquiring a new Syscoin masternode is approximately $16.5K USD. The tabulated 5-year projections of the case study in Tables 1–3 begins Jan 2023 at a conservative starting price of $0.25 USD per SYS. Using our Monte Carlo approach, we are projecting that one-month returns on a single node will be approximately $194 USD ($110 / $370) by Jan 2023 at a price of $0.43 USD per SYS, and $11,821 USD ($2,284 / $16,664) by Jan 2027 at a price of $16.87 USD per SYS.

The objective of Masternode Yield Farming is to allow operators to leverage masternode returns using an automated liquidity provider maintained by DAOSYS. The future intent is that this system will be generalized to the point where other crypto projects can leverage the returns on their masternodes. The details of which will be discussed at a later time. We are currently working to streamline the simulator so developers from other projects can setup simulations with their masternode system prior to making commitments.




